---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Deploy fail2ban config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Enable fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    state: started
